/**
*   Contains constants for action types.
*/

export const ADD_INPUT_BOX = 'ADD_INPUT_BOX'
export const REMOVE_INPUT_BOX = 'REMOVE_INPUT_BOX'
export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT'

export const DO_MERGE_REQUEST = 'DO_MERGE_REQUEST'
export const DO_MERGE_FAILURE = 'DO_MERGE_FAILURE'
export const DO_MERGE_SUCCESS = 'DO_MERGE_SUCCESS'
export const INVALIDATE_MERGE_RESULT = 'INVALIDATE_MERGE_RESULT'
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS'
export const UPDATE_MERGE_NAME = 'UPDATE_MERGE_NAME'
export const CLEAR_MERGE_FORM = 'CLEAR_MERGE_FORM'


export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SAVE_MERGE_REQUEST = 'SAVE_MERGE_REQUEST'
export const SAVE_MERGE_FAILURE = 'SAVE_MERGE_FAILURE'
export const SAVE_MERGE_SUCCESS = 'SAVE_MERGE_SUCCESS'


export const LOAD_MERGE_REQUEST = 'LOAD_MERGE_REQUEST'
export const LOAD_MERGE_FAILURE = 'LOAD_MERGE_FAILURE'
export const LOAD_MERGE_SUCCESS = 'LOAD_MERGE_SUCCESS'


export const LOAD_MERGE_LIST_REQUEST = 'LOAD_MERGE_LIST_REQUEST'
export const LOAD_MERGE_LIST_FAILURE = 'LOAD_MERGE_LIST_FAILURE'
export const LOAD_MERGE_LIST_SUCCESS = 'LOAD_MERGE_LIST_SUCCESS'



export const LOGIN_USERNAME_CHANGE ='LOGIN_USERNAME_CHANGE'
export const LOGIN_PASSWORD_CHANGE ='LOGIN_PASSWORD_CHANGE'


export const REGISTER_USERNAME_CHANGE ='REGISTER_USERNAME_CHANGE'
export const REGISTER_PASSWORD_CHANGE ='REGISTER_PASSWORD_CHANGE'

export const RECAPTCHA_VERIFY_RESPONSE ='RECAPTCHA_VERIFY_RESPONSE'


export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST'
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'

export const AUTH_FORM_ERROR = 'AUTH_FORM_ERROR'
export const AUTH_FORM_ALERT_DISMISS = 'AUTH_FORM_ALERT_DISMISS'

export const UPDATE_NAV_ACTIVE_KEY = 'UPDATE_NAV_ACTIVE_KEY'